#!/bin/bash

if [ -x "`which systemctl`" ] && ! uname -r | grep -i microsoft; then
    if [ "$1" != "upgrade" ]; then
        sudo systemctl stop fisk-daemon.service
        sudo systemctl stop fisk-daemon.socket
        sudo systemctl disable fisk-daemon.service
        sudo systemctl disable fisk-daemon.socket
    fi
fi
if [ "$1" != "upgrade" ]; then
    rm -rf /var/fisk/client/compilers
    rm -rf /usr/local/bin/fiskc
fi
if [ "$1" != "upgrade" ]; then
    rm -f /usr/local/bin/fisk-monitor
    rm -rf /var/fisk/daemon/node_modules
    rm -rf /var/fisk/daemon/data
    rm -f /var/fisk/daemon/package-lock.json

    MONITOR_DIR=/usr/local/fisk/monitor
    LINK_SRC="$MONITOR_DIR/node_modules/@andersbakken/fisk/monitor/fisk-monitor.js"
    if [ -L /usr/local/bin/fisk-monitor ] && [ "$(readlink /usr/local/bin/fisk-monitor)" = "$LINK_SRC" ]; then
        rm -f /usr/local/bin/fisk-monitor
    fi
    rm -rf $MONITOR_DIR
fi
