#!/bin/bash

mount | grep --quiet /mnt/fisk_objectcache_ram_drive && umount /mnt/fisk_objectcache_ram_drive
rm -rf /mnt/fisk_objectcache_ram_drive
rm -rf /var/fisk/builder/data
sudo service fisk-builder stop
if [ -x /var/fisk/builder/node/bin/npm ]; then
    /var/fisk/builder/node/bin/npm --unsafe-perm uninstall -g @andersbakken/fisk
fi
rm -rf /var/fisk/builder/node
sudo systemctl disable fisk-builder.service
